"use client";

import { AgentList, CreateAgentForm } from "@/components/agents";
import { Card } from "@/components/global";
import { useOwnedTreasuries } from "@/lib/hooks";

export default function AgentsPage() {
  const treasuriesQuery = useOwnedTreasuries();
  const treasuries = treasuriesQuery.data ?? [];

  return (
    <div className="mx-auto max-w-6xl space-y-10">
      <header className="space-y-3">
        <p className="eyebrow">AGENT VAULT</p>
        <h1 className="text-4xl font-semibold tracking-tight text-(--text-main)">
          Manage backend signer agents
        </h1>
        <p className="max-w-3xl text-sm leading-7 text-(--text-muted)">
          Agent keypairs are generated by the backend, encrypted at rest, and
          selected per session for dWallet, confidential, policy, and generic
          instruction flows.
        </p>
      </header>

      <Card hover={false} className="space-y-6">
        <div>
          <h2 className="text-xl font-semibold text-(--text-main)">
            Create Agent
          </h2>
          <p className="mt-2 text-sm text-(--text-muted)">
            The public key shown after creation is the `ai_authority` to use
            when creating new treasuries.
          </p>
        </div>
        <CreateAgentForm />
      </Card>

      <section className="space-y-5">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 className="text-xl font-semibold text-(--text-main)">
              Existing Agents
            </h2>
            <p className="mt-2 text-sm text-(--text-muted)">
              Select one agent before using backend signing routes.
            </p>
          </div>
          {treasuriesQuery.isFetching ? (
            <span className="font-mono text-[10px] uppercase tracking-widest text-(--text-muted)">
              Refreshing treasury links
            </span>
          ) : null}
        </div>
        <AgentList treasuries={treasuries} />
      </section>
    </div>
  );
}
