/** Generated AURA program error codes. Do not edit. */

export const AURA_ERROR_DEFINITIONS = [
  { code: 6000, name: "UnauthorizedAi", message: "unauthorized ai signer" },
  { code: 6001, name: "UnauthorizedOwner", message: "unauthorized owner" },
  {
    code: 6002,
    name: "UnauthorizedGuardian",
    message: "unauthorized guardian",
  },
  {
    code: 6003,
    name: "UnauthorizedExecutor",
    message: "unauthorized executor",
  },
  {
    code: 6004,
    name: "PendingTransactionExists",
    message: "pending transaction already exists",
  },
  {
    code: 6005,
    name: "NoPendingTransaction",
    message: "no pending transaction",
  },
  {
    code: 6006,
    name: "DWalletNotConfigured",
    message: "dwallet not configured for requested chain",
  },
  {
    code: 6007,
    name: "DWalletAlreadyRegistered",
    message: "dwallet already registered for requested chain",
  },
  { code: 6008, name: "PolicyGraphMismatch", message: "policy graph mismatch" },
  {
    code: 6009,
    name: "PolicyDigestMismatch",
    message: "policy digest mismatch",
  },
  {
    code: 6010,
    name: "DecryptionNotReady",
    message: "decryption result is not ready",
  },
  {
    code: 6011,
    name: "MessageApprovalNotReady",
    message: "message approval is not ready",
  },
  {
    code: 6012,
    name: "SignatureVerificationFailed",
    message: "signature verification failed",
  },
  {
    code: 6013,
    name: "InvalidDeployment",
    message: "invalid deployment configuration",
  },
  {
    code: 6014,
    name: "InvalidExternalAccountData",
    message: "invalid external account data",
  },
  {
    code: 6015,
    name: "ConfidentialGuardrailsNotConfigured",
    message: "confidential guardrails are not configured",
  },
  {
    code: 6016,
    name: "PolicyOutputNotReady",
    message: "encrypted policy output is not ready yet",
  },
  {
    code: 6017,
    name: "PolicyOutputAlreadyComputed",
    message: "encrypted policy output has already been computed",
  },
  { code: 6018, name: "ExecutionPaused", message: "execution is paused" },
  {
    code: 6019,
    name: "PendingTransactionExpired",
    message: "pending transaction expired",
  },
  { code: 6020, name: "NoActiveOverride", message: "no active override" },
  { code: 6021, name: "InvalidChain", message: "invalid chain value" },
  {
    code: 6022,
    name: "InvalidTransactionType",
    message: "invalid transaction type value",
  },
  { code: 6023, name: "InvalidCurve", message: "invalid curve value" },
  {
    code: 6024,
    name: "InvalidSignatureScheme",
    message: "invalid signature scheme value",
  },
  {
    code: 6025,
    name: "InvalidViolationCode",
    message: "invalid violation code",
  },
  {
    code: 6026,
    name: "InvalidProposalStatus",
    message: "invalid proposal status",
  },
  {
    code: 6027,
    name: "InvalidGuardianConfiguration",
    message: "invalid guardian configuration",
  },
  {
    code: 6028,
    name: "TimelockNotElapsed",
    message: "timelock period has not elapsed yet",
  },
  {
    code: 6029,
    name: "SanctionedAddress",
    message: "recipient address is on the sanctions list",
  },
  {
    code: 6030,
    name: "RecipientBlacklisted",
    message: "recipient address is blacklisted",
  },
  {
    code: 6031,
    name: "RecipientNotWhitelisted",
    message: "recipient address is not on the whitelist",
  },
  {
    code: 6032,
    name: "CooldownNotElapsed",
    message: "cooldown period between large transactions has not elapsed",
  },
  {
    code: 6033,
    name: "HighRiskTransactionRequiresGuardian",
    message: "high risk transaction requires guardian co-signature",
  },
  {
    code: 6034,
    name: "InvalidStateTransition",
    message: "invalid agent state transition",
  },
  {
    code: 6035,
    name: "ParentLimitExceeded",
    message: "parent treasury limit exceeded",
  },
  {
    code: 6036,
    name: "AnomalyDetected",
    message: "anomaly detected in transaction pattern",
  },
  {
    code: 6037,
    name: "SessionKeyInactive",
    message: "session key expired or revoked",
  },
  {
    code: 6038,
    name: "SessionKeyScopeViolation",
    message: "session key scope does not allow this proposal",
  },
  {
    code: 6039,
    name: "AccountStillActive",
    message: "account cannot be closed while still active",
  },
  {
    code: 6040,
    name: "BudgetEnvelopeLimitExceeded",
    message: "budget envelope limit exceeded",
  },
  {
    code: 6041,
    name: "ApprovalLevelNotSatisfied",
    message: "approval ladder level has not been satisfied",
  },
  {
    code: 6042,
    name: "PendingExecutionTimelockActive",
    message: "pending execution timelock is still active",
  },
  {
    code: 6043,
    name: "ExecutionScopePaused",
    message: "execution scope is paused",
  },
  {
    code: 6044,
    name: "OperatorRoleMissing",
    message: "operator role is missing required permission",
  },
  {
    code: 6045,
    name: "OperatorRoleExpired",
    message: "operator role has expired or was revoked",
  },
  {
    code: 6046,
    name: "ExternalDependencyStale",
    message: "external dependency freshness check failed",
  },
  {
    code: 6047,
    name: "InvalidPolicyPreset",
    message: "policy preset kind is invalid",
  },
  {
    code: 6048,
    name: "PolicyAttestationMismatch",
    message: "policy attestation hash or version mismatch",
  },
  { code: 6049, name: "EmptyBatch", message: "batch proposal cannot be empty" },
  {
    code: 6050,
    name: "BatchTooLarge",
    message: "batch proposal exceeds maximum item count",
  },
  {
    code: 6051,
    name: "ExposureGroupLimitExceeded",
    message: "cross-treasury exposure group limit exceeded",
  },
  {
    code: 6052,
    name: "ExposureGroupUnauthorized",
    message: "treasury is not a member of the exposure group",
  },
  {
    code: 6053,
    name: "BudgetEnvelopeNotFound",
    message: "budget envelope not found for the requested scope",
  },
  {
    code: 6054,
    name: "BudgetEnvelopeInUse",
    message: "budget envelope is referenced by an active pending proposal",
  },
  {
    code: 6055,
    name: "ExposureGroupNotEmpty",
    message: "exposure group still has members",
  },
  { code: 6056, name: "SwarmNotEmpty", message: "swarm still has members" },
  {
    code: 6057,
    name: "SwarmPoolUnsettled",
    message: "swarm pool balance is not settled",
  },
  {
    code: 6058,
    name: "LivenessGateActive",
    message: "liveness dependency is an active hard gate on policy",
  },
  {
    code: 6059,
    name: "RecipientLimitNotFound",
    message: "recipient limit not found for the requested chain and address",
  },
  {
    code: 6060,
    name: "AddressListEntryNotFound",
    message: "address list entry not found",
  },
  { code: 6061, name: "DWalletNotActive", message: "dwallet is not active" },
  { code: 6062, name: "DWalletFrozen", message: "dwallet is frozen" },
  {
    code: 6063,
    name: "DWalletHasActiveProposal",
    message: "dwallet has an active pending proposal on this chain",
  },
  {
    code: 6064,
    name: "DWalletLimitExceeded",
    message: "per-wallet spending limit exceeded",
  },
  {
    code: 6065,
    name: "DWalletNotEmpty",
    message: "dwallet still holds a balance",
  },
  { code: 6066, name: "DefaultChainInUse", message: "default chain is in use" },
  {
    code: 6067,
    name: "AssetNotTracked",
    message: "asset is not tracked on this dwallet",
  },
  {
    code: 6068,
    name: "InsufficientWalletBalance",
    message: "insufficient available wallet balance",
  },
  { code: 6069, name: "BalanceStale", message: "dwallet balance is stale" },
  {
    code: 6070,
    name: "TooManyAssets",
    message: "dwallet asset ledger is full",
  },
  {
    code: 6071,
    name: "ReservationUnderflow",
    message: "attempted to release more than is reserved",
  },
  {
    code: 6072,
    name: "InvalidTemplateConfig",
    message: "policy template config is incoherent",
  },
  {
    code: 6073,
    name: "TemplateNotShared",
    message: "policy template is not shared",
  },
  {
    code: 6074,
    name: "UnknownPolicyVersion",
    message: "parameterized override references an unknown policy field",
  },
  {
    code: 6075,
    name: "FailOpenBudgetExceeded",
    message: "fail-open budget exceeded for a softened check",
  },
  {
    code: 6076,
    name: "IntentDisabled",
    message: "scheduled intent is disabled",
  },
  {
    code: 6077,
    name: "IntentNotDue",
    message: "scheduled intent is not yet due",
  },
  {
    code: 6078,
    name: "IntentBudgetExhausted",
    message: "scheduled intent lifetime budget exhausted",
  },
  {
    code: 6079,
    name: "IntentRunsExhausted",
    message: "scheduled intent run count exhausted",
  },
  {
    code: 6080,
    name: "IntentExpired",
    message: "scheduled intent has expired",
  },
  {
    code: 6081,
    name: "UnauthorizedKeeper",
    message: "caller is not the authorized keeper",
  },
  {
    code: 6082,
    name: "InvalidIntentConfig",
    message: "scheduled intent recurrence or budget is invalid",
  },
  {
    code: 6083,
    name: "ConditionUnmet",
    message: "trigger conditions are not satisfied",
  },
  {
    code: 6084,
    name: "ConditionExpired",
    message: "conditional proposal expired before its conditions were met",
  },
  {
    code: 6085,
    name: "TooManyConditions",
    message: "too many trigger conditions",
  },
  { code: 6086, name: "OracleStale", message: "oracle price feed is stale" },
  {
    code: 6087,
    name: "OracleConfidenceTooWide",
    message: "oracle confidence interval is too wide",
  },
  {
    code: 6088,
    name: "UntrustedOracleProvider",
    message: "oracle provider is not trusted",
  },
  {
    code: 6089,
    name: "TrustedOracleRequired",
    message: "a trusted oracle provider is required",
  },
  {
    code: 6090,
    name: "OracleAccountInvalid",
    message: "oracle account is invalid",
  },
  {
    code: 6091,
    name: "OracleProviderNotAllowed",
    message: "oracle provider is not allowed",
  },
  {
    code: 6092,
    name: "ChainReplayFieldsMissing",
    message: "chain replay-protection fields are missing or invalid",
  },
  {
    code: 6093,
    name: "RecipientAddressInvalidForChain",
    message: "recipient address is invalid for the target chain",
  },
  {
    code: 6094,
    name: "SettlementNotConfirmed",
    message: "settlement has not been confirmed",
  },
  {
    code: 6095,
    name: "SettlementReorged",
    message: "settlement was reorged or failed",
  },
  {
    code: 6096,
    name: "ChainProfileNotRegistered",
    message: "chain profile is not registered or enabled",
  },
  {
    code: 6097,
    name: "TrustLockdownActive",
    message: "treasury is in trust lockdown; no proposals may be submitted",
  },
  {
    code: 6098,
    name: "InvalidTrustPolicy",
    message:
      "trust policy configuration is invalid (thresholds must be monotonic, multipliers ≤ 1×)",
  },
  {
    code: 6099,
    name: "TrustRestoreUnauthorized",
    message: "caller is not authorized to restore trust",
  },
  {
    code: 6100,
    name: "SuccessorNotNominated",
    message: "no successor owner has been nominated",
  },
  {
    code: 6101,
    name: "OwnershipHandoverTimelockActive",
    message: "ownership handover timelock has not elapsed",
  },
  {
    code: 6102,
    name: "AgentScopeExceeded",
    message: "proposal exceeds what this agent's scope permits",
  },
  { code: 6103, name: "AgentDisabled", message: "agent authority is disabled" },
  {
    code: 6104,
    name: "TooManyAgents",
    message: "treasury already has the maximum number of agent authorities",
  },
  {
    code: 6105,
    name: "UnauthorizedHandover",
    message: "caller is not authorized to execute the ownership handover",
  },
  {
    code: 6106,
    name: "AgentAlreadyRegistered",
    message: "an agent with this key is already registered",
  },
  {
    code: 6107,
    name: "AgentNotFound",
    message: "no agent with this key found on the treasury",
  },
  {
    code: 6108,
    name: "NoRecoveryDestination",
    message: "no recovery destination registered for this chain",
  },
  {
    code: 6109,
    name: "RecoveryTimelockActive",
    message: "recovery destination is locked; wait for the timelock to elapse",
  },
  {
    code: 6110,
    name: "RecoveryPreconditionNotMet",
    message:
      "break-glass preconditions not met: treasury is not in shutdown or activation window has not elapsed",
  },
  {
    code: 6111,
    name: "RecoveryDestinationImmutable",
    message:
      "recovery destination cannot be changed while an emergency shutdown is active",
  },
  {
    code: 6112,
    name: "UnauthorizedRecovery",
    message: "caller is not authorized to initiate a recovery operation",
  },
  {
    code: 6113,
    name: "DuplicateApprover",
    message: "approver has already approved this proposal",
  },
  {
    code: 6114,
    name: "ApprovalThresholdNotMet",
    message: "multi-party approval quorum has not been reached",
  },
  {
    code: 6115,
    name: "ApproverNotAuthorized",
    message: "signer is neither the owner nor a registered guardian",
  },
  {
    code: 6116,
    name: "ApprovalWeightInsufficient",
    message: "weighted approval quorum has not been reached",
  },
  {
    code: 6117,
    name: "AgentCapabilityExceeded",
    message: "action falls outside the agent's capability manifest",
  },
  {
    code: 6118,
    name: "ForbiddenInstructionForAgent",
    message: "agent attempted a privileged instruction it lacks",
  },
  {
    code: 6119,
    name: "AgentManifestLoosenTimelock",
    message: "manifest loosening attempted before its timelock elapsed",
  },
  {
    code: 6120,
    name: "InvalidAgentTripwires",
    message: "invalid agent tripwire configuration",
  },
  {
    code: 6121,
    name: "NoCandidatePolicy",
    message: "no candidate policy is staged for this treasury",
  },
  {
    code: 6122,
    name: "CanaryAlreadyActive",
    message: "a candidate policy is already being trialed",
  },
  {
    code: 6123,
    name: "CanarySampleFloorNotMet",
    message: "candidate has not collected the required number of samples",
  },
  {
    code: 6124,
    name: "UnauthorizedProtocolAuthority",
    message: "caller is not the protocol authority",
  },
  {
    code: 6125,
    name: "InvalidProtocolConfig",
    message: "protocol configuration values are invalid",
  },
  {
    code: 6126,
    name: "NoPendingProtocolUpdate",
    message: "no protocol configuration update is staged",
  },
  {
    code: 6127,
    name: "ProtocolUpdateTimelockActive",
    message: "protocol configuration update timelock has not elapsed",
  },
  {
    code: 6128,
    name: "InvalidFeeSchedule",
    message: "fee schedule fails coherence validation",
  },
  {
    code: 6129,
    name: "IntegratorFeeOutOfBounds",
    message: "integrator fee is outside the protocol-defined bounds",
  },
  {
    code: 6130,
    name: "DiscountExceedsProtocolFloor",
    message: "discount would reduce the fee below the protocol floor",
  },
  {
    code: 6131,
    name: "InsufficientFeeBalance",
    message: "prepaid fee balance cannot cover the fee",
  },
  {
    code: 6132,
    name: "FeeSplitsInvalid",
    message: "fee splits must sum to 10000 bps",
  },
  {
    code: 6133,
    name: "FeeConversionUnavailable",
    message: "fee conversion is unavailable (oracle stale)",
  },
  {
    code: 6134,
    name: "FeeDebtOutstanding",
    message: "fee debt is outstanding; settle before closing",
  },
  {
    code: 6135,
    name: "InvalidBillingTemplate",
    message: "billing template fails coherence validation",
  },
  {
    code: 6136,
    name: "OrgProfileComponentMissing",
    message: "org profile is missing a required component",
  },
  {
    code: 6137,
    name: "GuardrailEpochMismatch",
    message: "guardrail ciphertexts belong to a stale Encrypt epoch",
  },
  {
    code: 6138,
    name: "ConfidentialGuardrailsDisabled",
    message: "confidential guardrails are disabled",
  },
  {
    code: 6139,
    name: "GuardrailRotationRequired",
    message: "confidential guardrails require rotation before use",
  },
] as const;

export const AuraErrorCode = {
  UnauthorizedAi: 6000,
  UnauthorizedOwner: 6001,
  UnauthorizedGuardian: 6002,
  UnauthorizedExecutor: 6003,
  PendingTransactionExists: 6004,
  NoPendingTransaction: 6005,
  DWalletNotConfigured: 6006,
  DWalletAlreadyRegistered: 6007,
  PolicyGraphMismatch: 6008,
  PolicyDigestMismatch: 6009,
  DecryptionNotReady: 6010,
  MessageApprovalNotReady: 6011,
  SignatureVerificationFailed: 6012,
  InvalidDeployment: 6013,
  InvalidExternalAccountData: 6014,
  ConfidentialGuardrailsNotConfigured: 6015,
  PolicyOutputNotReady: 6016,
  PolicyOutputAlreadyComputed: 6017,
  ExecutionPaused: 6018,
  PendingTransactionExpired: 6019,
  NoActiveOverride: 6020,
  InvalidChain: 6021,
  InvalidTransactionType: 6022,
  InvalidCurve: 6023,
  InvalidSignatureScheme: 6024,
  InvalidViolationCode: 6025,
  InvalidProposalStatus: 6026,
  InvalidGuardianConfiguration: 6027,
  TimelockNotElapsed: 6028,
  SanctionedAddress: 6029,
  RecipientBlacklisted: 6030,
  RecipientNotWhitelisted: 6031,
  CooldownNotElapsed: 6032,
  HighRiskTransactionRequiresGuardian: 6033,
  InvalidStateTransition: 6034,
  ParentLimitExceeded: 6035,
  AnomalyDetected: 6036,
  SessionKeyInactive: 6037,
  SessionKeyScopeViolation: 6038,
  AccountStillActive: 6039,
  BudgetEnvelopeLimitExceeded: 6040,
  ApprovalLevelNotSatisfied: 6041,
  PendingExecutionTimelockActive: 6042,
  ExecutionScopePaused: 6043,
  OperatorRoleMissing: 6044,
  OperatorRoleExpired: 6045,
  ExternalDependencyStale: 6046,
  InvalidPolicyPreset: 6047,
  PolicyAttestationMismatch: 6048,
  EmptyBatch: 6049,
  BatchTooLarge: 6050,
  ExposureGroupLimitExceeded: 6051,
  ExposureGroupUnauthorized: 6052,
  BudgetEnvelopeNotFound: 6053,
  BudgetEnvelopeInUse: 6054,
  ExposureGroupNotEmpty: 6055,
  SwarmNotEmpty: 6056,
  SwarmPoolUnsettled: 6057,
  LivenessGateActive: 6058,
  RecipientLimitNotFound: 6059,
  AddressListEntryNotFound: 6060,
  DWalletNotActive: 6061,
  DWalletFrozen: 6062,
  DWalletHasActiveProposal: 6063,
  DWalletLimitExceeded: 6064,
  DWalletNotEmpty: 6065,
  DefaultChainInUse: 6066,
  AssetNotTracked: 6067,
  InsufficientWalletBalance: 6068,
  BalanceStale: 6069,
  TooManyAssets: 6070,
  ReservationUnderflow: 6071,
  InvalidTemplateConfig: 6072,
  TemplateNotShared: 6073,
  UnknownPolicyVersion: 6074,
  FailOpenBudgetExceeded: 6075,
  IntentDisabled: 6076,
  IntentNotDue: 6077,
  IntentBudgetExhausted: 6078,
  IntentRunsExhausted: 6079,
  IntentExpired: 6080,
  UnauthorizedKeeper: 6081,
  InvalidIntentConfig: 6082,
  ConditionUnmet: 6083,
  ConditionExpired: 6084,
  TooManyConditions: 6085,
  OracleStale: 6086,
  OracleConfidenceTooWide: 6087,
  UntrustedOracleProvider: 6088,
  TrustedOracleRequired: 6089,
  OracleAccountInvalid: 6090,
  OracleProviderNotAllowed: 6091,
  ChainReplayFieldsMissing: 6092,
  RecipientAddressInvalidForChain: 6093,
  SettlementNotConfirmed: 6094,
  SettlementReorged: 6095,
  ChainProfileNotRegistered: 6096,
  TrustLockdownActive: 6097,
  InvalidTrustPolicy: 6098,
  TrustRestoreUnauthorized: 6099,
  SuccessorNotNominated: 6100,
  OwnershipHandoverTimelockActive: 6101,
  AgentScopeExceeded: 6102,
  AgentDisabled: 6103,
  TooManyAgents: 6104,
  UnauthorizedHandover: 6105,
  AgentAlreadyRegistered: 6106,
  AgentNotFound: 6107,
  NoRecoveryDestination: 6108,
  RecoveryTimelockActive: 6109,
  RecoveryPreconditionNotMet: 6110,
  RecoveryDestinationImmutable: 6111,
  UnauthorizedRecovery: 6112,
  DuplicateApprover: 6113,
  ApprovalThresholdNotMet: 6114,
  ApproverNotAuthorized: 6115,
  ApprovalWeightInsufficient: 6116,
  AgentCapabilityExceeded: 6117,
  ForbiddenInstructionForAgent: 6118,
  AgentManifestLoosenTimelock: 6119,
  InvalidAgentTripwires: 6120,
  NoCandidatePolicy: 6121,
  CanaryAlreadyActive: 6122,
  CanarySampleFloorNotMet: 6123,
  UnauthorizedProtocolAuthority: 6124,
  InvalidProtocolConfig: 6125,
  NoPendingProtocolUpdate: 6126,
  ProtocolUpdateTimelockActive: 6127,
  InvalidFeeSchedule: 6128,
  IntegratorFeeOutOfBounds: 6129,
  DiscountExceedsProtocolFloor: 6130,
  InsufficientFeeBalance: 6131,
  FeeSplitsInvalid: 6132,
  FeeConversionUnavailable: 6133,
  FeeDebtOutstanding: 6134,
  InvalidBillingTemplate: 6135,
  OrgProfileComponentMissing: 6136,
  GuardrailEpochMismatch: 6137,
  ConfidentialGuardrailsDisabled: 6138,
  GuardrailRotationRequired: 6139,
} as const;

export type AuraErrorCodeType =
  (typeof AuraErrorCode)[keyof typeof AuraErrorCode];
