[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.13"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aura_core = "EaRoLVwL8EErDUeEMPHJ5QJeLVQZWJMtZcgmFzT9bhHs"

[programs.localnet]
aura_core = "EaRoLVwL8EErDUeEMPHJ5QJeLVQZWJMtZcgmFzT9bhHs"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/aura-core"]

[scripts]
test = "cargo test --workspace"

[hooks]
