/**
 * Canonical program-surface catalog for the current `aura-core` deployment.
 *
 * GENERATED by scripts/generate-sdk.js from the IDL + INSTRUCTION_DOMAINS map.
 * Do not edit by hand. Instruction names are snake_case to match the Anchor
 * IDL and on-chain logs. Apps use this metadata for navigation, capability
 * discovery, documentation, and command grouping.
 */

export type AuraFeatureDomainId =
  | "treasury"
  | "confidential"
  | "execution"
  | "governance"
  | "dwallet"
  | "policy"
  | "budget"
  | "operational"
  | "lifecycle"
  | "swarm"
  | "fees"
  | "address-lists"
  | "batch";

export type AuraFeatureMaturity =
  | "wallet"
  | "backend"
  | "read_only"
  | "external_cpi";

/** A single instruction exposed by the program, with display metadata. */
export interface AuraInstructionFeature {
  /** Anchor instruction name (snake_case). */
  name: string;
  /** Human readable command label. */
  label: string;
  /** Short operational summary. */
  description: string;
  /** How this instruction is usually driven. */
  maturity: AuraFeatureMaturity;
}

/** A domain groups related instructions for navigation and command grouping. */
export interface AuraFeatureDomain {
  id: AuraFeatureDomainId;
  label: string;
  description: string;
  instructions: AuraInstructionFeature[];
}

export const AURA_FEATURE_DOMAINS: AuraFeatureDomain[] = [
  {
    id: "treasury",
    label: "Treasury Lifecycle",
    description:
      "Create, migrate, and configure core treasury state, analytics, and recipient limits.",
    instructions: [
      {
        name: "close_treasury_analytics",
        label: "Close treasury analytics",
        description: "Close treasury analytics.",
        maturity: "wallet",
      },
      {
        name: "create_treasury",
        label: "Create treasury",
        description: "Create treasury.",
        maturity: "wallet",
      },
      {
        name: "init_treasury_analytics",
        label: "Init treasury analytics",
        description: "Init treasury analytics.",
        maturity: "wallet",
      },
      {
        name: "remove_recipient_limit",
        label: "Remove recipient limit",
        description: "Remove recipient limit.",
        maturity: "wallet",
      },
      {
        name: "set_recipient_limit",
        label: "Set recipient limit",
        description: "Set recipient limit.",
        maturity: "wallet",
      },
      {
        name: "update_treasury_metadata",
        label: "Update treasury metadata",
        description: "Update treasury metadata.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "confidential",
    label: "Confidential Execution",
    description:
      "Encrypted guardrails, FHE proposals, and the policy decryption flow.",
    instructions: [
      {
        name: "close_confidential_guardrails",
        label: "Close confidential guardrails",
        description: "Close confidential guardrails.",
        maturity: "external_cpi",
      },
      {
        name: "configure_confidential_guardrails",
        label: "Configure confidential guardrails",
        description: "Configure confidential guardrails.",
        maturity: "external_cpi",
      },
      {
        name: "confirm_policy_decryption",
        label: "Confirm policy decryption",
        description: "Confirm policy decryption.",
        maturity: "backend",
      },
      {
        name: "disable_confidential_guardrails",
        label: "Disable confidential guardrails",
        description: "Disable confidential guardrails.",
        maturity: "external_cpi",
      },
      {
        name: "init_confidential_guardrails",
        label: "Init confidential guardrails",
        description: "Init confidential guardrails.",
        maturity: "external_cpi",
      },
      {
        name: "propose_confidential_transaction",
        label: "Propose confidential transaction",
        description: "Propose confidential transaction.",
        maturity: "external_cpi",
      },
      {
        name: "request_policy_decryption",
        label: "Request policy decryption",
        description: "Request policy decryption.",
        maturity: "external_cpi",
      },
      {
        name: "reset_confidential_counters",
        label: "Reset confidential counters",
        description: "Reset confidential counters.",
        maturity: "external_cpi",
      },
      {
        name: "rotate_confidential_guardrails",
        label: "Rotate confidential guardrails",
        description: "Rotate confidential guardrails.",
        maturity: "external_cpi",
      },
      {
        name: "update_confidential_guardrails",
        label: "Update confidential guardrails",
        description: "Update confidential guardrails.",
        maturity: "external_cpi",
      },
    ],
  },
  {
    id: "execution",
    label: "Execution",
    description:
      "Public and conditional proposals, settlement, scheduled intents, and finalization.",
    instructions: [
      {
        name: "abandon_proposal",
        label: "Abandon proposal",
        description: "Abandon proposal.",
        maturity: "wallet",
      },
      {
        name: "approve_pending_execution",
        label: "Approve pending execution",
        description: "Approve pending execution.",
        maturity: "wallet",
      },
      {
        name: "cancel_pending",
        label: "Cancel pending",
        description: "Cancel pending.",
        maturity: "wallet",
      },
      {
        name: "clear_scheduled_intent_in_flight",
        label: "Clear scheduled intent in flight",
        description: "Clear scheduled intent in flight.",
        maturity: "wallet",
      },
      {
        name: "close_conditional_proposal",
        label: "Close conditional proposal",
        description: "Close conditional proposal.",
        maturity: "wallet",
      },
      {
        name: "close_scheduled_intent",
        label: "Close scheduled intent",
        description: "Close scheduled intent.",
        maturity: "wallet",
      },
      {
        name: "confirm_settlement",
        label: "Confirm settlement",
        description: "Confirm settlement.",
        maturity: "wallet",
      },
      {
        name: "create_scheduled_intent",
        label: "Create scheduled intent",
        description: "Create scheduled intent.",
        maturity: "wallet",
      },
      {
        name: "execute_pending",
        label: "Execute pending",
        description: "Execute pending.",
        maturity: "backend",
      },
      {
        name: "execute_scheduled_intent",
        label: "Execute scheduled intent",
        description: "Execute scheduled intent.",
        maturity: "backend",
      },
      {
        name: "finalize_execution",
        label: "Finalize execution",
        description: "Finalize execution.",
        maturity: "backend",
      },
      {
        name: "mark_settlement_broadcast",
        label: "Mark settlement broadcast",
        description: "Mark settlement broadcast.",
        maturity: "wallet",
      },
      {
        name: "pause_execution",
        label: "Pause execution",
        description: "Pause execution.",
        maturity: "wallet",
      },
      {
        name: "pause_scheduled_intent",
        label: "Pause scheduled intent",
        description: "Pause scheduled intent.",
        maturity: "wallet",
      },
      {
        name: "propose_conditional_transaction",
        label: "Propose conditional transaction",
        description: "Propose conditional transaction.",
        maturity: "wallet",
      },
      {
        name: "propose_transaction",
        label: "Propose transaction",
        description: "Propose transaction.",
        maturity: "wallet",
      },
      {
        name: "resubmit_proposal",
        label: "Resubmit proposal",
        description: "Resubmit proposal.",
        maturity: "wallet",
      },
      {
        name: "resume_scheduled_intent",
        label: "Resume scheduled intent",
        description: "Resume scheduled intent.",
        maturity: "wallet",
      },
      {
        name: "try_trigger",
        label: "Try trigger",
        description: "Try trigger.",
        maturity: "backend",
      },
      {
        name: "update_scheduled_intent",
        label: "Update scheduled intent",
        description: "Update scheduled intent.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "governance",
    label: "Governance",
    description:
      "Multisig, overrides, authority and guardian rotation, config changes, recovery, and shutdown.",
    instructions: [
      {
        name: "break_glass_recover",
        label: "Break glass recover",
        description: "Break glass recover.",
        maturity: "wallet",
      },
      {
        name: "break_glass_transfer_authority",
        label: "Break glass transfer authority",
        description: "Break glass transfer authority.",
        maturity: "wallet",
      },
      {
        name: "cancel_ai_rotation",
        label: "Cancel ai rotation",
        description: "Cancel ai rotation.",
        maturity: "wallet",
      },
      {
        name: "collect_override_signature",
        label: "Collect override signature",
        description: "Collect override signature.",
        maturity: "wallet",
      },
      {
        name: "configure_multisig",
        label: "Configure multisig",
        description: "Configure multisig.",
        maturity: "wallet",
      },
      {
        name: "emergency_shutdown",
        label: "Emergency shutdown",
        description: "Emergency shutdown.",
        maturity: "wallet",
      },
      {
        name: "execute_ai_rotation",
        label: "Execute ai rotation",
        description: "Execute ai rotation.",
        maturity: "wallet",
      },
      {
        name: "execute_config_change",
        label: "Execute config change",
        description: "Execute config change.",
        maturity: "wallet",
      },
      {
        name: "execute_guardian_rotation",
        label: "Execute guardian rotation",
        description: "Execute guardian rotation.",
        maturity: "wallet",
      },
      {
        name: "propose_ai_rotation",
        label: "Propose ai rotation",
        description: "Propose ai rotation.",
        maturity: "wallet",
      },
      {
        name: "propose_config_change",
        label: "Propose config change",
        description: "Propose config change.",
        maturity: "wallet",
      },
      {
        name: "propose_guardian_rotation",
        label: "Propose guardian rotation",
        description: "Propose guardian rotation.",
        maturity: "wallet",
      },
      {
        name: "propose_override",
        label: "Propose override",
        description: "Propose override.",
        maturity: "wallet",
      },
      {
        name: "register_recovery_destination",
        label: "Register recovery destination",
        description: "Register recovery destination.",
        maturity: "wallet",
      },
      {
        name: "veto_config_change",
        label: "Veto config change",
        description: "Veto config change.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "dwallet",
    label: "dWallet",
    description:
      "dWallet registration, runtime state, balances, oracle feeds, and spend reservations.",
    instructions: [
      {
        name: "init_dwallet_state",
        label: "Init dwallet state",
        description: "Init dwallet state.",
        maturity: "wallet",
      },
      {
        name: "reconcile_dwallet_balance",
        label: "Reconcile dwallet balance",
        description: "Reconcile dwallet balance.",
        maturity: "backend",
      },
      {
        name: "record_deposit",
        label: "Record deposit",
        description: "Record deposit.",
        maturity: "wallet",
      },
      {
        name: "refresh_asset_balance",
        label: "Refresh asset balance",
        description: "Refresh asset balance.",
        maturity: "backend",
      },
      {
        name: "refresh_dwallet_balance",
        label: "Refresh dwallet balance",
        description: "Refresh dwallet balance.",
        maturity: "backend",
      },
      {
        name: "refresh_verified_asset_balance",
        label: "Refresh verified asset balance",
        description: "Refresh verified asset balance.",
        maturity: "backend",
      },
      {
        name: "register_dwallet",
        label: "Register dwallet",
        description: "Register dwallet.",
        maturity: "wallet",
      },
      {
        name: "release_dwallet_spend",
        label: "Release dwallet spend",
        description: "Release dwallet spend.",
        maturity: "wallet",
      },
      {
        name: "remove_dwallet",
        label: "Remove dwallet",
        description: "Remove dwallet.",
        maturity: "wallet",
      },
      {
        name: "reserve_dwallet_spend",
        label: "Reserve dwallet spend",
        description: "Reserve dwallet spend.",
        maturity: "wallet",
      },
      {
        name: "rotate_dwallet_authority",
        label: "Rotate dwallet authority",
        description: "Rotate dwallet authority.",
        maturity: "wallet",
      },
      {
        name: "set_asset_feed",
        label: "Set asset feed",
        description: "Set asset feed.",
        maturity: "wallet",
      },
      {
        name: "set_asset_oracle_feed",
        label: "Set asset oracle feed",
        description: "Set asset oracle feed.",
        maturity: "wallet",
      },
      {
        name: "set_default_chain",
        label: "Set default chain",
        description: "Set default chain.",
        maturity: "wallet",
      },
      {
        name: "set_dwallet_label",
        label: "Set dwallet label",
        description: "Set dwallet label.",
        maturity: "wallet",
      },
      {
        name: "set_dwallet_limits",
        label: "Set dwallet limits",
        description: "Set dwallet limits.",
        maturity: "wallet",
      },
      {
        name: "set_dwallet_status",
        label: "Set dwallet status",
        description: "Set dwallet status.",
        maturity: "wallet",
      },
      {
        name: "settle_dwallet_spend",
        label: "Settle dwallet spend",
        description: "Settle dwallet spend.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "policy",
    label: "Policy Services",
    description:
      "Presets, templates, simulations, receipts, attestations, history, canaries, and trust.",
    instructions: [
      {
        name: "apply_policy_preset",
        label: "Apply policy preset",
        description: "Apply policy preset.",
        maturity: "wallet",
      },
      {
        name: "apply_policy_template",
        label: "Apply policy template",
        description: "Apply policy template.",
        maturity: "wallet",
      },
      {
        name: "apply_policy_template_parameterized",
        label: "Apply policy template parameterized",
        description: "Apply policy template parameterized.",
        maturity: "wallet",
      },
      {
        name: "attest_policy",
        label: "Attest policy",
        description: "Attest policy.",
        maturity: "wallet",
      },
      {
        name: "check_invariants",
        label: "Check invariants",
        description: "Check invariants.",
        maturity: "wallet",
      },
      {
        name: "check_policy_cpi",
        label: "Check policy cpi",
        description: "Check policy cpi.",
        maturity: "backend",
      },
      {
        name: "close_policy_history",
        label: "Close policy history",
        description: "Close policy history.",
        maturity: "wallet",
      },
      {
        name: "close_policy_template",
        label: "Close policy template",
        description: "Close policy template.",
        maturity: "wallet",
      },
      {
        name: "configure_trust_policy",
        label: "Configure trust policy",
        description: "Configure trust policy.",
        maturity: "wallet",
      },
      {
        name: "create_policy_template",
        label: "Create policy template",
        description: "Create policy template.",
        maturity: "wallet",
      },
      {
        name: "discard_canary",
        label: "Discard canary",
        description: "Discard canary.",
        maturity: "wallet",
      },
      {
        name: "init_policy_history",
        label: "Init policy history",
        description: "Init policy history.",
        maturity: "wallet",
      },
      {
        name: "init_trust_identity",
        label: "Init trust identity",
        description: "Init trust identity.",
        maturity: "wallet",
      },
      {
        name: "promote_canary",
        label: "Promote canary",
        description: "Promote canary.",
        maturity: "wallet",
      },
      {
        name: "record_policy_snapshot",
        label: "Record policy snapshot",
        description: "Record policy snapshot.",
        maturity: "wallet",
      },
      {
        name: "restore_trust",
        label: "Restore trust",
        description: "Restore trust.",
        maturity: "wallet",
      },
      {
        name: "rollback_policy",
        label: "Rollback policy",
        description: "Rollback policy.",
        maturity: "wallet",
      },
      {
        name: "simulate_policy",
        label: "Simulate policy",
        description: "Simulate policy.",
        maturity: "wallet",
      },
      {
        name: "start_canary",
        label: "Start canary",
        description: "Start canary.",
        maturity: "wallet",
      },
      {
        name: "update_policy_template",
        label: "Update policy template",
        description: "Update policy template.",
        maturity: "wallet",
      },
      {
        name: "write_policy_receipt",
        label: "Write policy receipt",
        description: "Write policy receipt.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "budget",
    label: "Budgets & Exposure",
    description:
      "Budget envelopes, exposure groups, approval ladders, and liveness guardrails.",
    instructions: [
      {
        name: "close_exposure_group",
        label: "Close exposure group",
        description: "Close exposure group.",
        maturity: "wallet",
      },
      {
        name: "configure_approval_ladder",
        label: "Configure approval ladder",
        description: "Configure approval ladder.",
        maturity: "wallet",
      },
      {
        name: "configure_budget_envelope",
        label: "Configure budget envelope",
        description: "Configure budget envelope.",
        maturity: "wallet",
      },
      {
        name: "configure_liveness_guardrails",
        label: "Configure liveness guardrails",
        description: "Configure liveness guardrails.",
        maturity: "wallet",
      },
      {
        name: "init_exposure_group",
        label: "Init exposure group",
        description: "Init exposure group.",
        maturity: "wallet",
      },
      {
        name: "join_exposure_group",
        label: "Join exposure group",
        description: "Join exposure group.",
        maturity: "wallet",
      },
      {
        name: "leave_exposure_group",
        label: "Leave exposure group",
        description: "Leave exposure group.",
        maturity: "wallet",
      },
      {
        name: "remove_budget_envelope",
        label: "Remove budget envelope",
        description: "Remove budget envelope.",
        maturity: "wallet",
      },
      {
        name: "update_exposure_group",
        label: "Update exposure group",
        description: "Update exposure group.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "operational",
    label: "Operations",
    description:
      "Scoped pauses, external liveness, health scores, snapshots, and activity logs.",
    instructions: [
      {
        name: "close_activity_log",
        label: "Close activity log",
        description: "Close activity log.",
        maturity: "wallet",
      },
      {
        name: "close_external_liveness",
        label: "Close external liveness",
        description: "Close external liveness.",
        maturity: "wallet",
      },
      {
        name: "close_health_score",
        label: "Close health score",
        description: "Close health score.",
        maturity: "wallet",
      },
      {
        name: "close_snapshot",
        label: "Close snapshot",
        description: "Close snapshot.",
        maturity: "wallet",
      },
      {
        name: "init_activity_log",
        label: "Init activity log",
        description: "Init activity log.",
        maturity: "wallet",
      },
      {
        name: "init_external_liveness",
        label: "Init external liveness",
        description: "Init external liveness.",
        maturity: "wallet",
      },
      {
        name: "init_health_score",
        label: "Init health score",
        description: "Init health score.",
        maturity: "wallet",
      },
      {
        name: "refresh_external_liveness",
        label: "Refresh external liveness",
        description: "Refresh external liveness.",
        maturity: "backend",
      },
      {
        name: "refresh_health_score",
        label: "Refresh health score",
        description: "Refresh health score.",
        maturity: "backend",
      },
      {
        name: "set_scoped_pause",
        label: "Set scoped pause",
        description: "Set scoped pause.",
        maturity: "wallet",
      },
      {
        name: "take_snapshot",
        label: "Take snapshot",
        description: "Take snapshot.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "lifecycle",
    label: "Lifecycle & Roles",
    description:
      "Agent identity and capabilities, ownership, operator roles, session keys, chain and protocol config.",
    instructions: [
      {
        name: "arm_capability_loosen",
        label: "Arm capability loosen",
        description: "Arm capability loosen.",
        maturity: "wallet",
      },
      {
        name: "close_session_key",
        label: "Close session key",
        description: "Close session key.",
        maturity: "wallet",
      },
      {
        name: "commit_protocol_config",
        label: "Commit protocol config",
        description: "Commit protocol config.",
        maturity: "wallet",
      },
      {
        name: "emergency_revoke_agent",
        label: "Emergency revoke agent",
        description: "Emergency revoke agent.",
        maturity: "wallet",
      },
      {
        name: "execute_ownership_handover",
        label: "Execute ownership handover",
        description: "Execute ownership handover.",
        maturity: "wallet",
      },
      {
        name: "grant_operator_role",
        label: "Grant operator role",
        description: "Grant operator role.",
        maturity: "wallet",
      },
      {
        name: "init_protocol_config",
        label: "Init protocol config",
        description: "Init protocol config.",
        maturity: "wallet",
      },
      {
        name: "issue_session_key",
        label: "Issue session key",
        description: "Issue session key.",
        maturity: "wallet",
      },
      {
        name: "migrate_treasury",
        label: "Migrate treasury",
        description: "Migrate treasury.",
        maturity: "wallet",
      },
      {
        name: "nominate_successor_owner",
        label: "Nominate successor owner",
        description: "Nominate successor owner.",
        maturity: "wallet",
      },
      {
        name: "register_agent",
        label: "Register agent",
        description: "Register agent.",
        maturity: "wallet",
      },
      {
        name: "register_chain_profile",
        label: "Register chain profile",
        description: "Register chain profile.",
        maturity: "wallet",
      },
      {
        name: "revoke_agent",
        label: "Revoke agent",
        description: "Revoke agent.",
        maturity: "wallet",
      },
      {
        name: "revoke_operator_role",
        label: "Revoke operator role",
        description: "Revoke operator role.",
        maturity: "wallet",
      },
      {
        name: "revoke_session_key",
        label: "Revoke session key",
        description: "Revoke session key.",
        maturity: "wallet",
      },
      {
        name: "set_agent_capability",
        label: "Set agent capability",
        description: "Set agent capability.",
        maturity: "wallet",
      },
      {
        name: "set_agent_tripwires",
        label: "Set agent tripwires",
        description: "Set agent tripwires.",
        maturity: "wallet",
      },
      {
        name: "transition_agent_state",
        label: "Transition agent state",
        description: "Transition agent state.",
        maturity: "wallet",
      },
      {
        name: "trigger_dead_mans_switch",
        label: "Trigger dead mans switch",
        description: "Trigger dead mans switch.",
        maturity: "backend",
      },
      {
        name: "update_chain_profile",
        label: "Update chain profile",
        description: "Update chain profile.",
        maturity: "wallet",
      },
      {
        name: "update_operator_role",
        label: "Update operator role",
        description: "Update operator role.",
        maturity: "wallet",
      },
      {
        name: "update_protocol_config",
        label: "Update protocol config",
        description: "Update protocol config.",
        maturity: "wallet",
      },
      {
        name: "update_session_key",
        label: "Update session key",
        description: "Update session key.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "swarm",
    label: "Swarm Pools",
    description: "Shared agent-pool initialization and membership.",
    instructions: [
      {
        name: "close_swarm_pool",
        label: "Close swarm pool",
        description: "Close swarm pool.",
        maturity: "wallet",
      },
      {
        name: "configure_swarm",
        label: "Configure swarm",
        description: "Configure swarm.",
        maturity: "wallet",
      },
      {
        name: "init_swarm_pool",
        label: "Init swarm pool",
        description: "Init swarm pool.",
        maturity: "wallet",
      },
      {
        name: "join_swarm",
        label: "Join swarm",
        description: "Join swarm.",
        maturity: "wallet",
      },
      {
        name: "leave_swarm",
        label: "Leave swarm",
        description: "Leave swarm.",
        maturity: "wallet",
      },
      {
        name: "update_swarm",
        label: "Update swarm",
        description: "Update swarm.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "fees",
    label: "Protocol Fees",
    description:
      "Fee schedules, vaults, billing templates, collection, and payouts.",
    instructions: [
      {
        name: "apply_billing_template",
        label: "Apply billing template",
        description: "Apply billing template.",
        maturity: "wallet",
      },
      {
        name: "apply_org_profile",
        label: "Apply org profile",
        description: "Apply org profile.",
        maturity: "wallet",
      },
      {
        name: "close_billing_template",
        label: "Close billing template",
        description: "Close billing template.",
        maturity: "wallet",
      },
      {
        name: "close_fee_schedule",
        label: "Close fee schedule",
        description: "Close fee schedule.",
        maturity: "wallet",
      },
      {
        name: "close_fee_vault",
        label: "Close fee vault",
        description: "Close fee vault.",
        maturity: "wallet",
      },
      {
        name: "collect_fees",
        label: "Collect fees",
        description: "Collect fees.",
        maturity: "backend",
      },
      {
        name: "create_billing_template",
        label: "Create billing template",
        description: "Create billing template.",
        maturity: "wallet",
      },
      {
        name: "deposit_fees",
        label: "Deposit fees",
        description: "Deposit fees.",
        maturity: "wallet",
      },
      {
        name: "init_fee_schedule",
        label: "Init fee schedule",
        description: "Init fee schedule.",
        maturity: "wallet",
      },
      {
        name: "init_fee_vault",
        label: "Init fee vault",
        description: "Init fee vault.",
        maturity: "wallet",
      },
      {
        name: "set_fee_splits",
        label: "Set fee splits",
        description: "Set fee splits.",
        maturity: "wallet",
      },
      {
        name: "update_billing_template",
        label: "Update billing template",
        description: "Update billing template.",
        maturity: "wallet",
      },
      {
        name: "update_fee_recipient",
        label: "Update fee recipient",
        description: "Update fee recipient.",
        maturity: "wallet",
      },
      {
        name: "update_fee_schedule",
        label: "Update fee schedule",
        description: "Update fee schedule.",
        maturity: "wallet",
      },
      {
        name: "withdraw_unused_fees",
        label: "Withdraw unused fees",
        description: "Withdraw unused fees.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "address-lists",
    label: "Address Lists",
    description: "Allow and deny lists for recipients and contracts.",
    instructions: [
      {
        name: "clear_address_list",
        label: "Clear address list",
        description: "Clear address list.",
        maturity: "wallet",
      },
      {
        name: "close_address_list",
        label: "Close address list",
        description: "Close address list.",
        maturity: "wallet",
      },
      {
        name: "init_address_list",
        label: "Init address list",
        description: "Init address list.",
        maturity: "wallet",
      },
      {
        name: "manage_address_list",
        label: "Manage address list",
        description: "Manage address list.",
        maturity: "wallet",
      },
      {
        name: "update_address_list_entry",
        label: "Update address list entry",
        description: "Update address list entry.",
        maturity: "wallet",
      },
    ],
  },
  {
    id: "batch",
    label: "Batch",
    description: "Batch policy simulation and proposal records.",
    instructions: [
      {
        name: "propose_batch",
        label: "Propose batch",
        description: "Propose batch.",
        maturity: "wallet",
      },
      {
        name: "propose_confidential_batch",
        label: "Propose confidential batch",
        description: "Propose confidential batch.",
        maturity: "external_cpi",
      },
    ],
  },
];

/** Flat list of every instruction feature, annotated with its domain. */
export const AURA_INSTRUCTION_FEATURES: (AuraInstructionFeature & {
  domain: AuraFeatureDomainId;
  domainLabel: string;
})[] = AURA_FEATURE_DOMAINS.flatMap((domain) =>
  domain.instructions.map((instruction) => ({
    ...instruction,
    domain: domain.id,
    domainLabel: domain.label,
  })),
);

/** Complete instruction-name -> domain id map (all 161 instructions). */
export const AURA_INSTRUCTION_DOMAINS: Record<string, AuraFeatureDomainId> = {
  abandon_proposal: "execution",
  apply_billing_template: "fees",
  apply_org_profile: "fees",
  apply_policy_preset: "policy",
  apply_policy_template: "policy",
  apply_policy_template_parameterized: "policy",
  approve_pending_execution: "execution",
  arm_capability_loosen: "lifecycle",
  attest_policy: "policy",
  break_glass_recover: "governance",
  break_glass_transfer_authority: "governance",
  cancel_ai_rotation: "governance",
  cancel_pending: "execution",
  check_invariants: "policy",
  check_policy_cpi: "policy",
  clear_address_list: "address-lists",
  clear_scheduled_intent_in_flight: "execution",
  close_activity_log: "operational",
  close_address_list: "address-lists",
  close_billing_template: "fees",
  close_conditional_proposal: "execution",
  close_confidential_guardrails: "confidential",
  close_exposure_group: "budget",
  close_external_liveness: "operational",
  close_fee_schedule: "fees",
  close_fee_vault: "fees",
  close_health_score: "operational",
  close_policy_history: "policy",
  close_policy_template: "policy",
  close_scheduled_intent: "execution",
  close_session_key: "lifecycle",
  close_snapshot: "operational",
  close_swarm_pool: "swarm",
  close_treasury_analytics: "treasury",
  collect_fees: "fees",
  collect_override_signature: "governance",
  commit_protocol_config: "lifecycle",
  configure_approval_ladder: "budget",
  configure_budget_envelope: "budget",
  configure_confidential_guardrails: "confidential",
  configure_liveness_guardrails: "budget",
  configure_multisig: "governance",
  configure_swarm: "swarm",
  configure_trust_policy: "policy",
  confirm_policy_decryption: "confidential",
  confirm_settlement: "execution",
  create_billing_template: "fees",
  create_policy_template: "policy",
  create_scheduled_intent: "execution",
  create_treasury: "treasury",
  deposit_fees: "fees",
  disable_confidential_guardrails: "confidential",
  discard_canary: "policy",
  emergency_revoke_agent: "lifecycle",
  emergency_shutdown: "governance",
  execute_ai_rotation: "governance",
  execute_config_change: "governance",
  execute_guardian_rotation: "governance",
  execute_ownership_handover: "lifecycle",
  execute_pending: "execution",
  execute_scheduled_intent: "execution",
  finalize_execution: "execution",
  grant_operator_role: "lifecycle",
  init_activity_log: "operational",
  init_address_list: "address-lists",
  init_confidential_guardrails: "confidential",
  init_dwallet_state: "dwallet",
  init_exposure_group: "budget",
  init_external_liveness: "operational",
  init_fee_schedule: "fees",
  init_fee_vault: "fees",
  init_health_score: "operational",
  init_policy_history: "policy",
  init_protocol_config: "lifecycle",
  init_swarm_pool: "swarm",
  init_treasury_analytics: "treasury",
  init_trust_identity: "policy",
  issue_session_key: "lifecycle",
  join_exposure_group: "budget",
  join_swarm: "swarm",
  leave_exposure_group: "budget",
  leave_swarm: "swarm",
  manage_address_list: "address-lists",
  mark_settlement_broadcast: "execution",
  migrate_treasury: "lifecycle",
  nominate_successor_owner: "lifecycle",
  pause_execution: "execution",
  pause_scheduled_intent: "execution",
  promote_canary: "policy",
  propose_ai_rotation: "governance",
  propose_batch: "batch",
  propose_conditional_transaction: "execution",
  propose_confidential_batch: "batch",
  propose_confidential_transaction: "confidential",
  propose_config_change: "governance",
  propose_guardian_rotation: "governance",
  propose_override: "governance",
  propose_transaction: "execution",
  reconcile_dwallet_balance: "dwallet",
  record_deposit: "dwallet",
  record_policy_snapshot: "policy",
  refresh_asset_balance: "dwallet",
  refresh_dwallet_balance: "dwallet",
  refresh_external_liveness: "operational",
  refresh_health_score: "operational",
  refresh_verified_asset_balance: "dwallet",
  register_agent: "lifecycle",
  register_chain_profile: "lifecycle",
  register_dwallet: "dwallet",
  register_recovery_destination: "governance",
  release_dwallet_spend: "dwallet",
  remove_budget_envelope: "budget",
  remove_dwallet: "dwallet",
  remove_recipient_limit: "treasury",
  request_policy_decryption: "confidential",
  reserve_dwallet_spend: "dwallet",
  reset_confidential_counters: "confidential",
  restore_trust: "policy",
  resubmit_proposal: "execution",
  resume_scheduled_intent: "execution",
  revoke_agent: "lifecycle",
  revoke_operator_role: "lifecycle",
  revoke_session_key: "lifecycle",
  rollback_policy: "policy",
  rotate_confidential_guardrails: "confidential",
  rotate_dwallet_authority: "dwallet",
  set_agent_capability: "lifecycle",
  set_agent_tripwires: "lifecycle",
  set_asset_feed: "dwallet",
  set_asset_oracle_feed: "dwallet",
  set_default_chain: "dwallet",
  set_dwallet_label: "dwallet",
  set_dwallet_limits: "dwallet",
  set_dwallet_status: "dwallet",
  set_fee_splits: "fees",
  set_recipient_limit: "treasury",
  set_scoped_pause: "operational",
  settle_dwallet_spend: "dwallet",
  simulate_policy: "policy",
  start_canary: "policy",
  take_snapshot: "operational",
  transition_agent_state: "lifecycle",
  trigger_dead_mans_switch: "lifecycle",
  try_trigger: "execution",
  update_address_list_entry: "address-lists",
  update_billing_template: "fees",
  update_chain_profile: "lifecycle",
  update_confidential_guardrails: "confidential",
  update_exposure_group: "budget",
  update_fee_recipient: "fees",
  update_fee_schedule: "fees",
  update_operator_role: "lifecycle",
  update_policy_template: "policy",
  update_protocol_config: "lifecycle",
  update_scheduled_intent: "execution",
  update_session_key: "lifecycle",
  update_swarm: "swarm",
  update_treasury_metadata: "treasury",
  veto_config_change: "governance",
  withdraw_unused_fees: "fees",
  write_policy_receipt: "policy",
};

/** Looks up a domain definition by id. */
export function getAuraFeatureDomain(
  id: AuraFeatureDomainId,
): AuraFeatureDomain | undefined {
  return AURA_FEATURE_DOMAINS.find((domain) => domain.id === id);
}

/** Returns the domain id for an instruction name, or undefined if unknown. */
export function getInstructionDomain(
  name: string,
): AuraFeatureDomainId | undefined {
  return AURA_INSTRUCTION_DOMAINS[name];
}
